// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl5QLOwtdCfNPL33SWTkfk2iXEyeOB7R8',
    appId: '1:765691399796:web:606fd6e43d7398f6610b21',
    messagingSenderId: '765691399796',
    projectId: 'chat--app-6f8d5',
    authDomain: 'chat--app-6f8d5.firebaseapp.com',
    storageBucket: 'chat--app-6f8d5.appspot.com',
    measurementId: 'G-T4TKJYMRCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDhNVNt_Mfz9BsRXQTM_-h9uX2J2xZTuk',
    appId: '1:765691399796:android:8f164f71d005af01610b21',
    messagingSenderId: '765691399796',
    projectId: 'chat--app-6f8d5',
    storageBucket: 'chat--app-6f8d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABZKanXwY2MWv7LTdRpCrshVLmVPTg71Y',
    appId: '1:765691399796:ios:ef1675b7bcf7c70f610b21',
    messagingSenderId: '765691399796',
    projectId: 'chat--app-6f8d5',
    storageBucket: 'chat--app-6f8d5.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABZKanXwY2MWv7LTdRpCrshVLmVPTg71Y',
    appId: '1:765691399796:ios:ef1675b7bcf7c70f610b21',
    messagingSenderId: '765691399796',
    projectId: 'chat--app-6f8d5',
    storageBucket: 'chat--app-6f8d5.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl5QLOwtdCfNPL33SWTkfk2iXEyeOB7R8',
    appId: '1:765691399796:web:3e9f838ae74996c8610b21',
    messagingSenderId: '765691399796',
    projectId: 'chat--app-6f8d5',
    authDomain: 'chat--app-6f8d5.firebaseapp.com',
    storageBucket: 'chat--app-6f8d5.appspot.com',
    measurementId: 'G-ZNBJWY9LJW',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAl5QLOwtdCfNPL33SWTkfk2iXEyeOB7R8',
    appId: '1:765691399796:web:780be6f8cc0cc2d4610b21',
    messagingSenderId: '765691399796',
    projectId: 'chat--app-6f8d5',
    authDomain: 'chat--app-6f8d5.firebaseapp.com',
    storageBucket: 'chat--app-6f8d5.appspot.com',
    measurementId: 'G-3Y2DZ44WD7',
  );
}
